### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xiaofengtongxue** [taomujian/linbing#1]
[error] 4102#0: *65 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: 127.0.0.1, request: "POST /api/query HTTP/1.0", upstream: "uwsgi://0.0.0.0:8000", host: "127.0.0.1:8800", 

不知道为啥出现这个问题

**Comment by taomujian** [comment]
这是进行什么操作时出现的问题？其它操作有这个问题吗?

**Comment by xiaofengtongxue** [comment]
运行起来后，进行页面注册的时候

**Comment by taomujian** [comment]
uwsgi.ini这个文件中的配置修改过吗？

**Comment by xiaofengtongxue** [comment]
配置过

**Comment by taomujian** [comment]
https://blog.csdn.net/fsj818077/article/details/85243145,看下这篇文章呢,
socket = 127.0.0.1:8001     # 这个是被访问地址，十分重要，因为后续的nginx访问后端链接地址就是 这个地址，而不是http地址，必须注意，否则nignx的log就会显示以下错误：

upstream prematurely closed connection while reading response header from upstre    am, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:8080", host: "127.0.0.1"

**Comment by xiaofengtongxue** [comment]
uwsgi.ini中已经有了socket，这个错误主要在注册模块

**Comment by taomujian** [comment]
这个错误的主要原因可能是你修改过uwsgi.ini文件，能否把你的uwsgi.ini配置文件和nginx的配置，截图发下呢
