### ISSUE TITLE
docker编译镜像报错

### ISSUE THREAD

**Issue by Pretexts** [taomujian/linbing#11]
Nothing to configure.
Ignoring colorama: markers 'sys_platform == "win32"' don't match your environment
Ignoring win32-setctime: markers 'sys_platform == "win32"' don't match your environment
Collecting cx-Oracle (from -r /root/flask/requirements.txt (line 2))
  Could not find a version that satisfies the requirement cx-Oracle (from -r /root/flask/requirements.txt (line 2)) (from versions: )
No matching distribution found for cx-Oracle (from -r /root/flask/requirements.txt (line 2))
The command '/bin/sh -c service mysql start && mysql -e "SET PASSWORD FOR root@localhost = PASSWORD('123456');FLUSH PRIVILEGES;" && mysql -e "update mysql.user set plugin='mysql_native_password' where User='123456';FLUSH PRIVILEGES;" && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1 && update-alternatives --config python3 && pip3 install -r /root/flask/requirements.txt && chmod +x /ubuntu_run.sh' returned a non-zero code: 1

**Comment by Pretexts** [comment]
![image](https://user-images.githubusercontent.com/29346963/100436249-0fbd4c80-30da-11eb-9293-b5aa96bf271c.png)

**Comment by Hopeless** [comment]
兄弟是32位系统？

**Comment by taomujian** [comment]
是的,应该是你的网络问题,我刚重试了下,没有问题呢
