### ISSUE TITLE
无法发送邮件

### ISSUE THREAD

**Issue by 0ps** [taomujian/linbing#12]
`(535, b'Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
[pid: 291|app: 0|req: 1/1] 127.0.0.1 () {52 vars in 907 bytes} [Sat Dec 19 02:49:22 2020] POST /api/getchecknum => generated 62 bytes in 621 msecs (HTTP/1.0 200) 5 headers in 183 bytes (1 switches on core 0)`

smtp的信息肯定是对的，但是就是无法成功“{'code': 'Z1003', 'message': '发送邮件异常', 'data': ''}”，建议内置一个帐号，因为这样的系统也就一两个人使用。

**Comment by taomujian** [comment]
这个代码不是新的哦，新的已经采用安装postfix,使用postfix来发邮件了，无需再填写邮箱登陆接口了

**Comment by 0ps** [comment]
我使用的docker安装

**Comment by taomujian** [comment]
代码已经更新了,请使用最新的代码尝试
