### ISSUE TITLE
你好作者我在部署的时候有几个问题需要你的帮助。

### ISSUE THREAD

**Issue by lfqevf4** [taomujian/linbing#13]
`第一个问题，在ubuntu上部署之成功之后postfix也部署成功了，但是项目运行之后需要注册的时候收不到验证码查看了mail的log发现如下的错误
`root@vultr:~# tail /var/log/mail.log
Jan 15 09:17:10 vultr postfix/cleanup[48911]: 197361FDB71: message-id=<20210115091710.197361FDB71@vultr.guest>
Jan 15 09:17:10 vultr postfix/smtpd[48908]: disconnect from localhost[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
Jan 15 09:17:10 vultr postfix/qmgr[48494]: 197361FDB71: from=<**linbing@xip.io**>, size=782, nrcpt=1 (queue active)
Jan 15 09:17:12 vultr postfix/smtp[48912]: 197361FDB71: to=<7777777777@qq.com>, relay=smtp.qq.com[203.205.232.7]:465, delay=2.1, delays=0.01/0.02/1.8/0.28, dsn=5.0.0, status=bounced (host smtp.qq.com[203.205.232.7] said: 501 Mail from address must be same as authorization user. (in reply to MAIL FROM command))
Jan 15 09:17:14 vultr postfix/smtp[48912]: 2C89B1FDC55: to=<linbing@xip.io>, relay=smtp.qq.com[203.205.232.7]:465, delay=2.1, delays=0/0/1.8/0.24, dsn=5.0.0, status=bounced (host smtp.qq.com[203.205.232.7] said: 502 Invalid paramenters (in reply to MAIL FROM command))`
我不知道这个linbing@xip.io在哪里修改，按照你的配置教程所说在flask目录下的conf.ini来配置邮箱及授权码，可是实在是没看出来怎么配置的，conf.ini的内容如下：
[mysql]
ip = 127.0.0.1
port = 3306
username = root
password = 1234567

[Aes]
key = FejK34f214s03szb
iv = L9A242fGmJn9o1xn

[request]
proxy = 
timeout = 5

应该如何配置呢，
第二点docker的我也搭建了一套也是同一个问题我不知道在哪里配置邮箱及授权码。
我是一个小白，请大佬指点一二，感谢~~~~

**Comment by taomujian** [comment]
你好,发送邮件失败看错误信息是你写的这个7777777777@qq.com这个地址并不存在,另外也有原因是邮箱被qq邮箱给拦截了,需要去自助收信里查询下有没有收到,需要把linbing@xip.io给加到白名单,

**Comment by taomujian** [comment]
修改发送邮箱的话,在run.py第38行修改

**Comment by taomujian** [comment]
正在重新构建新版本,新版本已取消注册机制,敬请期待～～～
