### ISSUE TITLE
无法执行扫描所有未开始目标

### ISSUE THREAD

**Issue by MrTcsy** [taomujian/linbing#14]
报错：

请求失败
系统异常,请稍后重新尝试!

**Comment by MrTcsy** [comment]
和目标数量应该没有关系，目标只有一条或者几条的时候依然无法执行此操作，必须要手动一个个去执行

**Comment by taomujian** [comment]
后台日志内容是什么呢？/var/log/gunicorn_error.log，这个文件

**Comment by taomujian** [comment]
好的，这个问题已修复，过几天会重新发布
