### ISSUE TITLE
是否可以上传一下程序的图片供参考呢？

### ISSUE THREAD

**Issue by ExpLang-CN** [taomujian/linbing#2]
是否可以上传一下程序的图片供参考呢？

**Comment by taomujian** [comment]
![RJW%}A1( NXVTAOBEYH_$F](https://user-images.githubusercontent.com/47107775/79301114-42378200-7f1b-11ea-8ba2-a8f97447512c.png)
![3YWJB `SVL2C`0E)0Q9B8](https://user-images.githubusercontent.com/47107775/79301116-44014580-7f1b-11ea-9e7c-f586e240bd66.png)
![9HW9RA}EYJ6VZM4L9` B7](https://user-images.githubusercontent.com/47107775/79301118-4499dc00-7f1b-11ea-99c6-c18bfd83b756.png)
![G9UY @ `A$G8D(~QOL(E%0Q](https://user-images.githubusercontent.com/47107775/79301120-45327280-7f1b-11ea-9423-d234f41dccd4.png)
![T2$O{V}I`SXWE0HZPR2FFM2](https://user-images.githubusercontent.com/47107775/79301121-45cb0900-7f1b-11ea-96ac-8b579a906186.png)
![T2}6XHZ58S$JIGGN)5KU$F9](https://user-images.githubusercontent.com/47107775/79301123-46639f80-7f1b-11ea-8c7c-42820f8ebf87.png)
![BQ1PYD QI87 5UT(XJEX{KE](https://user-images.githubusercontent.com/47107775/79301144-5c716000-7f1b-11ea-8e65-ca50315634bb.png)
页面基本上是这样
