### ISSUE TITLE
资产管理这一项没有数据

### ISSUE THREAD

**Issue by Lgr00** [taomujian/linbing#21]
您好，请问 资产管理这一项应该怎么使用呢？  经过一些测试后发现还是没有数据显示。我是在ubuntu中手动搭建的环境
有测试案例可以提供下吗
![image](https://user-images.githubusercontent.com/131250759/233777537-0761270a-3636-4e6d-a230-d41996d95d81.png)

**Comment by taomujian** [comment]
选择目标进行端口扫描后，会把端口扫描的结果保存到数据库里，资产管理就是用来展示端口扫描的结果的。先看下有没有进行端口扫描呢
