### ISSUE TITLE
容器启动时候报错

### ISSUE THREAD

**Issue by SaltNego** [taomujian/linbing#24]
[root@VM-0-3-centos ~]# docker run -it -d -p 11000:11000 -p 8800:8800 taomujian/linbing
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested
956b6a8d34b9dfd6c7946fa50e2f4b3cc0e189da3f372bc7895c5aa886985b1e
[root@VM-0-3-centos ~]# uname -a
Linux VM-0-3-centos 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
[root@VM-0-3-centos ~]#

**Comment by taomujian** [comment]
这个是告警，不影响的吧？后续没有成功吗？按说容器是独立存在的，和宿主机关系不大

**Comment by taomujian** [comment]
> [root@VM-0-3-centos ~]# docker run -it -d -p 11000:11000 -p 8800:8800 taomujian/linbing WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested 956b6a8d34b9dfd6c7946fa50e2f4b3cc0e189da3f372bc7895c5aa886985b1e [root@VM-0-3-centos ~]# uname -a Linux VM-0-3-centos 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux [root@VM-0-3-centos ~]#

已修复，编译镜像时没有考虑架构问题，请重新下载最新镜像。
