### ISSUE TITLE
容器启动就退出没法常驻

### ISSUE THREAD

**Issue by SaltNego** [taomujian/linbing#25]
![image](https://github.com/taomujian/linbing/assets/19511250/b34e1352-bcf1-47fa-8d6e-6e2b35e54629)

容器启动就退出没法常驻，
师傅请问一下该如何解决

**Comment by taomujian** [comment]
镜像id是最新的吗？最新的为dd1e26e52734, 如果使用的docker用加速服务了，要看下镜像是否对得上

**Comment by taomujian** [comment]
> ![image](https://private-user-images.githubusercontent.com/19511250/260309289-b34e1352-bcf1-47fa-8d6e-6e2b35e54629.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDQ3NjYsIm5iZiI6MTcxNDQ0NDQ2NiwicGF0aCI6Ii8xOTUxMTI1MC8yNjAzMDkyODktYjM0ZTEzNTItYmNmMS00N2ZhLThkNmUtNmUyYjM1ZTU0NjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDAyMzQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYWNjOTcyNmNlMzUwNTZlODVlMjZkYzhjNzAyYmQwMTk3NGFlMDhmZmI0MzM1YWY0MzZiNWM5MDFhODY5MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6uCF54RfiDTZX1UJsrEmzQ_eYmhk8GN39G5TbdZ8LX0)
> 
> 容器启动就退出没法常驻， 师傅请问一下该如何解决

已修复，编译镜像时没有考虑架构问题，请重新下载最新镜像。
