### ISSUE TITLE
自己打包ubuntu.docker后运行登录提示404

### ISSUE THREAD

**Issue by bjgetite** [taomujian/linbing#28]
根据ubuntu.dockerfile打包得镜像，运行后查看日志
 * Starting MariaDB database server mysqld                               [ OK ] 
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
Starting redis-server: redis-server.

进容器验证mysql和redis密码都正常，通过页面输入用户名密码后提示404，post提交http://127.0.0.1:11000/api/login这个地址404，有可能是后端服务没启动？

**进入容器手动执行了**
nohup python3 worker.py > log.log 2>&1 &
nohup gunicorn -c gunicorn.conf main:app -k uvicorn.workers.UvicornWorker > gunicorn.log 2>&1 &
还是不行。
**gunicorn.log提示**
WARNING: configuration file should have a valid Python extension.
**log.log无报错**
`14:07:33 Worker rq:worker:d15b52c542b640e7bb908c459e20a1c1 started with PID 417, version 1.15.1
14:07:33 Worker rq:worker:901f67bacdab4b5b8872ce8f4024b9f7 started with PID 416, version 1.15.1
14:07:33 Subscribing to channel rq:pubsub:d15b52c542b640e7bb908c459e20a1c1
14:07:33 Subscribing to channel rq:pubsub:901f67bacdab4b5b8872ce8f4024b9f7
14:07:33 *** Listening on high...
14:07:33 *** Listening on high...`

**Comment by taomujian** [comment]
后端没啥问题,大概率nginx和gunicorn没对上

**Comment by taomujian** [comment]
重新试下从dockerhub中获取镜像呢
