### ISSUE TITLE
Docker 启动报错

### ISSUE THREAD

**Issue by yingfeng-i** [taomujian/linbing#32]
从DockerHub拉的镜像，起不来

报错信息如下：

```
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
add8a68199e393920f0c2ec05076586fa5b2f47e3a65729a53b0c93095480ede

```

![图片](https://github.com/taomujian/linbing/assets/18555737/94cb2036-503a-487a-a5a0-b82039a5d564)

Docker 日志

`standard_init_linux.go:228: exec user process caused: exec format error`

似乎是构建映像的时候没有加上linux/amd64平台？

**Comment by freshgeek** [comment]
我这边是 exec /ubuntu_docker_run.sh: exec format error

**Comment by J-Snowwite** [comment]
就是没有生成amd 版本的docker ,估计作者是在mac 笔记本上搞得

**Comment by taomujian** [comment]
> 从DockerHub拉的镜像，起不来
> 
> 报错信息如下：
> 
> ```
> WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
> add8a68199e393920f0c2ec05076586fa5b2f47e3a65729a53b0c93095480ede
> ```
> 
> ![图片](https://private-user-images.githubusercontent.com/18555737/296649936-94cb2036-503a-487a-a5a0-b82039a5d564.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0Mzk5NTEsIm5iZiI6MTcxNDQzOTY1MSwicGF0aCI6Ii8xODU1NTczNy8yOTY2NDk5MzYtOTRjYjIwMzYtNTAzYS00ODdhLWE1YTAtYjgyMDM5YTVkNTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDAxMTQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNjY5ZDRkZTZmM2EzYzkwY2E4YzEzNmZjODk0MmYzNmM4Y2ExNmIyOTQzMWZhMmEzYjYxNDhiZDk3MmNjNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.okDtm0TWNmUlBfRA5R1MIQdgdy9Q5tLRAyDaUQoshTs)
> 
> Docker 日志
> 
> `standard_init_linux.go:228: exec user process caused: exec format error`
> 
> 似乎是构建映像的时候没有加上linux/amd64平台？

是的，已修复，编译镜像时没有考虑架构问题，请重新下载最新镜像。

**Comment by taomujian** [comment]
> 我这边是 exec /ubuntu_docker_run.sh: exec format error

已修复，编译镜像时没有考虑架构问题，请重新下载最新镜像。

**Comment by taomujian** [comment]
> 就是没有生成amd 版本的docker ,估计作者是在mac 笔记本上搞得

是的，太菜了，也没有好好测试，编译镜像还有架构的问题，已修复，编译镜像时没有考虑架构问题，请重新下载最新镜像。
