### ISSUE TITLE
容器运行502

### ISSUE THREAD

**Issue by xiaoguaidel** [taomujian/linbing#35]
容器运行502
![image](https://github.com/taomujian/linbing/assets/51114917/eac92cc1-5e6d-45d3-9e49-2bcba6f71b56)

**Comment by taomujian** [comment]
是从docker hub上拉取的镜像吗？是的话，看下载的镜像id是不是1a8a454ea13881542bc17db3259feb9aba8e281dc9944e57bb981ad061151d0f
