### ISSUE TITLE
验证码有误

### ISSUE THREAD

**Issue by autumn1023** [taomujian/linbing#5]
提示验证码，有误，试了多次还是提示有误

**Comment by taomujian** [comment]
第一次可能会有点慢，导致发多次，肯能会混乱，重新启动下试试呢

**Comment by autumn1023** [comment]
大佬，重启还是没有生效，nginx，uwsgi没有异常日志。

**Comment by autumn1023** [comment]
![image](https://user-images.githubusercontent.com/19710386/83384812-9c809980-a41a-11ea-8115-cc84a8e4a429.png)

**Comment by taomujian** [comment]
在后台输出下生成的验证码，到再到日志里去看下，看下输出的验证码和你接收到的是否一致,run.py的第147就是返回的结果

**Comment by autumn1023** [comment]
@autumn1023 生成的验证：capta，与收到的验证，是一致的。

**Comment by autumn1023** [comment]
![Uploading image.png…]()

**Comment by autumn1023** [comment]
<app.sendmail.MailSender object at 0x7f11f478eba8>
-----
abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
b
-----
bB
-----
bBk
-----
bBkV
-----
bBkVr
-----
bBkVrj
-----
验证码
bBkVrj
bBkVrj
bBkVrj
bBkVrj
bBkVrj
('Z1000', 'bBkVrj')
('Z1000', 'bBkVrj')
('Z1000', 'bBkVrj')
('Z1000', 'bBkVrj')
{'code': 'Z1000', 'message': '请求成功', 'data': ''}
[pid: 965696|app: 0|req: 7/8] 127.0.0.1 () {56 vars in 1016 bytes} [Mon Jun  8 14:58:43 2020] POST /api/getchecknum => generated 56 bytes in 828 msecs (HTTP/1.0 200) 5 headers in 190 bytes (1 switches on core 3)

**Comment by autumn1023** [comment]
![image](https://user-images.githubusercontent.com/19710386/84139318-392de180-aa82-11ea-9195-64c9614e502a.png)

**Comment by taomujian** [comment]
还是不能注册？

**Comment by autumn1023** [comment]
验证还是通过不了，是不是前端有问题

**Comment by taomujian** [comment]
应该不会的，之前验证码我测试的时候没出过问题，浏览器缓存清一下呢

**Comment by taomujian** [comment]
在浏览器控制台看下flask返回给前端的验证码是否和后端发送的，邮件收到的一致呢

**Comment by autumn1023** [comment]
{'code': 'Z1000', 'message': '请求成功', 'data': ''}

**Comment by taomujian** [comment]
老兄，我邮箱，taomujian@protonmail,我们用邮箱联系下吧。。

**Comment by kingsec666** [comment]
安装出个手册吧

**Comment by taomujian** [comment]
好的，好的，我再整理下

**Comment by kingsec666** [comment]
这周结束部署的问题吧     star已经给了！

**Comment by taomujian** [comment]
基本的部署文档,readme文档就写的很清楚了,至于为啥会失败的原因,我也不清楚，这周我再看下

**Comment by taomujian** [comment]
现在可以了，之前因为考虑安全性问题，有个逻辑不通的地方
