### ISSUE TITLE
安装成功后，配置好邮箱smtp后无法发送验证码

### ISSUE THREAD

**Issue by fumengze** [taomujian/linbing#8]
获取验证码时直接返回502了

**Comment by taomujian** [comment]
邮箱收到邮件了吗？uwsgi日志是什么呢？

**Comment by fumengze** [comment]
没有收到邮件，服务端返回502 Bad Gateway   
日志：


*** Starting uWSGI 2.0.18 (64bit) on [Thu Jul 30 09:50:56 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 13 May 2020 17:24:14
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: fmz-centos-01
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /root/linbing/linbing-master/flask
detected binary path: /usr/sbin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7230
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (0.0.0.0:8000).
bind(): Address already in use [core/socket.c line 769]
-- unavailable modifier requested: 0 --

**Comment by taomujian** [comment]
显示你的8000端口已被占用，你把使用8000端口的进程杀死，然后重启uwsgi

**Comment by fumengze** [comment]
这是我在重启uwsgi时的问题，--reload  和杀死进程然后 重启  uwsgi.ini也试过了。但还是同样的结果，应该是nginx的问题。
这是nginx的报错

2020/07/30 10:46:33 [error] 1307#0: *734 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /api/getchecknum HTTP/1.0", upstream: "uwsgi://0.0.0.0:8000", host: "127.0.0.1:8800", referrer: "http://192.168.102.229:11000/register"
2020/07/30 10:46:36 [error] 1306#0: *737 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /api/getchecknum HTTP/1.0", upstream: "uwsgi://0.0.0.0:8000", host: "127.0.0.1:8800", referrer: "http://192.168.102.229:11000/register"
2020/07/30 10:46:43 [error] 1307#0: *740 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /api/query HTTP/1.0", upstream: "uwsgi://0.0.0.0:8000", host: "127.0.0.1:8800", referrer: "http://192.168.102.229:11000/register"
2020/07/30 10:46:43 [error] 1306#0: *743 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /api/query HTTP/1.0", upstream: "uwsgi://0.0.0.0:8000", host: "127.0.0.1:8800", referrer: "http://192.168.102.229:11000/register"
2020/07/30 10:46:46 [error] 1307#0: *746 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /api/getchecknum HTTP/1.0", upstream: "uwsgi://0.0.0.0:8000", host: "127.0.0.1:8800", referrer: "http://192.168.102.229:11000/register"
2020/07/30 10:47:18 [error] 1305#0: *750 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /api/getchecknum HTTP/1.0", upstream: "uwsgi://0.0.0.0:8000", host: "127.0.0.1:8800", referrer: "http://192.168.102.229:11000/register"

**Comment by taomujian** [comment]
uwsgi 还是显示probably another instance of uWSGI is running on the same address (0.0.0.0:8000).
bind(): Address already in use [core/socket.c line 769]
-- unavailable modifier requested: 0 --?

**Comment by taomujian** [comment]
我刚重新试了下，发现了一个其它的问题，并不是这个问题，已经修改了，已经修改好了

**Comment by fumengze** [comment]
我查看了端口占用的进程就是 uwsgi在使用8000端口

**Comment by taomujian** [comment]
默认的配置uwsgi 是使用的8000端口,uwsgi会有5个进程使用8000端口,都杀死了吗？

**Comment by taomujian** [comment]
怎么联系你？你邮箱多少？

**Comment by fumengze** [comment]
www154883422@163.com
